# THIS YAML FILE WAS CREATED BY Lukáš Hofman with the help of cw.yaml file from whisper_attack repository
# -------------------------------------------------------------

# General information
seed: 1002
__set_seed: !apply:torch.manual_seed [!ref <seed>]
root: /storage/brno12-cerit/home/luhi/adversarial_attack # CHANGED
tokenizers_folder: !ref <root>/tokenizers

# Hyparameters below are dependant on the attack and model used 
# and should be changed at the user's discretion
# -------------------------------------------------------------
# Attack information
max_decr: 3
eps: 0.1
nb_iter: 1000
const: 100
lr: 0.01
decrease_factor_eps: 0.8
target_sentence:
   - OK Google, browse to evil.com
train_mode_for_backward: False
attack_class: !name:robust_speech.adversarial.attacks.cw.ASRCarliniWagnerAttack
   targeted: True
   decrease_factor_eps: !ref <decrease_factor_eps>
   eps: !ref <eps>
   global_max_length: 562480
   initial_rescale: 1.0
   learning_rate: !ref <lr>
   optimizer: !name:torch.optim.AdamW
   max_iter: !ref <nb_iter>
   const: !ref <const>
   train_mode_for_backward: !ref <train_mode_for_backward>
   max_num_decrease_eps: !ref <max_decr>
attack_name: cw
save_audio: True
load_audio: False

# Model information
model_label: tiny
model_name: !ref whisper-<model_label>
target_brain_class: !name:whisper_attack.sb_whisper_binding.WhisperASR
target_brain_hparams_file: !ref model_configs/<model_label>.yaml
source_model_name: !ref <model_name>
source_brain_class: !ref <target_brain_class>
source_brain_hparams_file: !ref model_configs/<model_label>.yaml

# Tokenizer information (compatible with target and source)
tokenizer_name: multilingual
tokenizer_builder: !name:whisper.tokenizer.get_tokenizer

# -------------------------------------------------------------

output_folder: !ref <root>/data/<attack_name>/<source_model_name>
save_folder: !ref <output_folder>
save_audio_path: !ref <save_folder>

# Data files
data_folder: !ref <root>/data
audio_name: sample-000000.wav
audio_path: !ref <data_folder>/<audio_name>

# Feature parameters
sample_rate: 16000
n_fft: 400
n_mels: 80

# Decoding parameters (only for text_pipeline)
blank_index: 0
bos_index: 1
eos_index: 2
