# THIS YAML FILE WAS CREATED BY Lukáš Hofman based on the other .yaml files from whisper_attack repository
# -------------------------------------------------------------


# General information
seed: 1002
__set_seed: !apply:torch.manual_seed [!ref <seed>]
root: !PLACEHOLDER
tokenizers_folder: !ref <root>/tokenizers

# -------------------------------------------------------------
# Attack information
nb_iter: 200
population_size: 50
eps: 0.01
attack_class: !name:robust_speech.adversarial.attacks.genetic.GeneticAttack
  nb_iter: !ref <nb_iter>
  population_size: !ref <population_size>
  eps: !ref <eps>
  targeted: False
save_audio: True
load_audio: True
attack_name: genetic

# Model information
model_label: tiny
model_name: !ref whisper-<model_label>
target_brain_class: !name:whisper_attack.sb_whisper_binding.WhisperASR
target_brain_hparams_file: !ref model_configs/<model_label>.yaml
source_model_name: !ref <model_name>
source_brain_class: !ref <target_brain_class>
source_brain_hparams_file: !ref model_configs/<model_label>.yaml

# Tokenizer information
tokenizer_name: multilingual
tokenizer_builder: !name:whisper.tokenizer.get_tokenizer

# Output
output_folder: !ref <root>/attacks/<attack_name>/<source_model_name>/<seed>
wer_file: !ref <output_folder>/wer.txt
save_folder: !ref <output_folder>
log: !ref <output_folder>/log.txt
save_audio_path: !ref <output_folder>/save

# Data
dataset_prepare_fct: !name:robust_speech.data.librispeech.prepare_librispeech
dataio_prepare_fct: !name:robust_speech.data.dataio.dataio_prepare
data_folder: !ref <root>/data/LibriSpeech
csv_folder: !ref <data_folder>/csv
test_splits: ["test-clean"]
skip_prep: True
data_csv_name: test-clean
test_csv:
   - !ref <data_folder>/csv/<data_csv_name>.csv
batch_size: 1
avoid_if_longer_than: 14.0
sorting: random

# Feature parameters
sample_rate: 16000
n_fft: 400
n_mels: 80

# Decoding parameters
blank_index: 0
bos_index: 1
eos_index: 2

test_dataloader_opts:
    batch_size: 1

logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <log>
